### PR TITLE
Fix VoxelOctree.h missing <vector> / <cstddef> includes

### LINKED ISSUE #1833: VoxelOctree.h: missing #include <vector> and <cstddef> breaks UE 5.7 source-build compile
## Bug

`Source/CesiumRuntime/Private/VoxelOctree.h` uses `std::vector<std::byte>` in `UVoxelOctreeTexture` member function signatures (lines 34, 94, 153, 289) but does not `#include <vector>` or `#include <cstddef>`. The header relies on a transitive include chain that no longer holds for everyone — UE 5.7's source-build clang 20.1.8 toolchain doesn't pull `<vector>` in via the chain Cesium for Unreal expects.

The bug was introduced by #1685 ("Add basic support for voxel rendering and styling") and shipped in v2.25.0. v2.26.0 and the current `main` branch (`8c9a93c…`) still contain the same code unchanged.

It only surfaces when UnrealBuildTool recompiles the plugin from source, which happens on UE source builds. Users on Launcher / binary UE installs link the prebuilt `.so` Cesium ships and never hit it — which is presumably why Cesium's own CI hasn't caught it.

## Repro

Environment:

* Unreal Engine **5.7.4-release** built from source (Epic GitHub mirror, SHA `260bb2e1c5610b31c63a36206eedd289409c5f11`).
* UE-bundled LLVM toolchain `v26_clang-20.1.8-rockylinux8` (the one pinned by `Engine/Config/Linux/Linux_SDK.json`).
* Cesium for Unreal v2.25.0 (also reproduced on v2.26.0; `VoxelOctree.{h,cpp}` are unchanged between the releases).
* A C++ project that enables `CesiumForUnreal` and triggers a source rebuild of the plugin via `Build.sh <Target> Linux Development -Project=<.uproject>`.

```
$ ~/regulus/UnrealEngine/Engine/Build/BatchFiles/Linux/Build.sh \
      MyEditor Linux Development -Project=$PWD/MyProject.uproject
```

## Errors

```
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.h:34:43:
  error: no template named 'vector' in namespace 'std'; did you mean 'Arctor'?
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.h:94:7:
  error: expected parameter declarator
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.h:153:7:
  error: no template named 'vector' in namespace 'std'
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.h:289:3:
  error: no template named 'vector' in namespace 'std'

Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.cpp:72:27:
  error: out-of-line definition of 'update' does not match any declaration in 'UVoxelOctreeTexture'
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.cpp:138:27:
  error: out-of-line definition of 'insertNodeData' does not match any declaration in 'UVoxelOctreeTexture'
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.cpp:158:27:
  error: out-of-line definition of 'encodeNode' does not match any declaration in 'UVoxelOctreeTexture'
Engine/Plugins/Marketplace/CesiumForUnreal/Source/CesiumRuntime/Private/VoxelOctree.cpp:173:9:
  error: too many arguments to function call, expected 0, have 4
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

The `Arctor` typo-correction is from clang's `--show-suggestions` — it's a UE custom container reachable via `CoreMinimal.h`. The cascade of "out-of-line definition does not match" + "too many arguments" errors is downstream: when `std::vector` doesn't parse, the in-class member declarations are malformed, and the .cpp's matching out-of-line definitions can't bind to them.

## Fix

Adding `#include <vector>` and `#include <cstddef>` to `VoxelOctree.h` resolves the entire cascade. Verified locally — `Build.sh OfanimEditor Linux Development` succeeds with 0 errors after the change; only `VoxelOctree.cpp` rebuilds (24-second turnaround).

Diff:

```diff
--- a/Source/CesiumRuntime/Private/VoxelOctree.h
+++ b/Source/CesiumRuntime/Private/VoxelOctree.h
@@ -6,8 +6,10 @@
 #include "RenderCommandFence.h"

 #include <CesiumGeometry/OctreeTileID.h>
+#include <cstddef>
 #include <optional>
 #include <unordered_map>
+#include <vector>

 class FVoxelOctree;
```

I'll open a PR with this diff. Happy to add Cesium's standard copyright header bump or any other formatting / convention you prefer.

## Why this didn't show up before

* Cesium's binary CI tests against Launcher UE, where the prebuilt `.so` is used and the source isn't recompiled.
* Earlier UE versions or earlier clang versions in the bundled toolchain may have transitively exposed `<vector>` through the `CoreMinimal.h` chain — clang 20.1.8 in the v26 toolchain doesn't.
* Cesium 2.25.0 was released 2026-04-01; UE 5.7.4-release shipped its v26 toolchain pin in late April. The combination is recent.

A precedent: the v2.24.0 changelog notes a similar header-include fix for `CesiumCartographicPolygon.cpp` and `CesiumMetadataValue.h` introduced in v2.23.0 — same shape of bug, same toolchain-update trigger.

## Searched before filing

I searched the issues tracker for `VoxelOctree`, `Arctor`, `vector namespace std`, `clang 20`, `5.7.4`, and `missing include` — no existing report. Also searched the Cesium community forum and general web — no matches. Filing this issue together with a PR.

### PR DESCRIPTION
**Pull request by gzharun**
## Summary

Adds the missing `#include <vector>` and `#include <cstddef>` to `Source/CesiumRuntime/Private/VoxelOctree.h`.

Closes #1833.

## Why

`VoxelOctree.h` uses `std::vector<std::byte>` in `UVoxelOctreeTexture` member function signatures at lines 34, 94, 153, 289. The header was relying on a transitive include chain that doesn't hold under UE 5.7's bundled clang 20.1.8 toolchain — `<vector>` isn't reachable through the `CoreMinimal.h` chain on that compiler. Issue #1833 has the full error transcript and toolchain context.

The bug was introduced by #1685 ("Add basic support for voxel rendering and styling") in v2.25.0 and persists in v2.26.0 and on `main` (`8c9a93c`). It only surfaces when UnrealBuildTool recompiles the plugin from source — UE source-build users hit it; Launcher UE users link the prebuilt `.so` and never see it, which is presumably why Cesium's CI hasn't caught it. Same shape as the v2.24.0 changelog entry "Added missing includes in `CesiumCartographicPolygon.cpp` and `CesiumMetadataValue.h`, introduced in v2.23.0."

## Fix

```diff
--- a/Source/CesiumRuntime/Private/VoxelOctree.h
+++ b/Source/CesiumRuntime/Private/VoxelOctree.h
@@ -6,8 +6,10 @@
 #include "RenderCommandFence.h"

 #include <CesiumGeometry/OctreeTileID.h>
+#include <cstddef>
 #include <optional>
 #include <unordered_map>
+#include <vector>
```

Plus a CHANGES.md entry under the unreleased section.

## Verification

Reproduced the failure on **UE 5.7.4-release source build** + bundled clang 20.1.8 (`v26_clang-20.1.8-rockylinux8` toolchain). Twenty distinct error lines from this single missing include — the parser fails on the in-class member declarations using `std::vector<std::byte>`, then the .cpp's out-of-line definitions can't bind to broken declarations, producing the cascade of "out-of-line definition does not match" and "too many arguments to function call" errors documented in #1833.

After the include fix:

```
[Adaptive Build] … VoxelOctree.cpp …
[1/8] Compile VoxelOctree.cpp
Result: Succeeded
Total execution time: 24.44 seconds
```

Single TU rebuild; no other source changes triggered. The cascade was downstream of the missing includes; nothing else needed to change.

## Notes for reviewers

- I'm a UE-source-build user hitting this in my own project's adapter (not a Cesium developer). Filing the issue + PR together; happy to follow Cesium's contribution conventions on commit message format / sign-off / formatting if there's something I missed.
- No CI-detectable behavior change for binary-plugin users — the prebuilt `.so` is unaffected.

### CODE REVIEW

**Comment by j9liu** [comment]
Hi @gzharun, thanks for the catch and the PR!

In order for us to review and merge your code, we need a signed [Contributor License Agreement (CLA)](https://github.com/CesiumGS/community/tree/main/CLAs) from you. Let us know once this is done. Thanks!

**Comment by j9liu** [comment]
Hey @gzharun! Just wanted to bump my above comment, in case you missed it.

**Comment by gzharun** [comment]
Hi @j9liu, done!

**Review by j9liu — APPROVED** [review]
Looks great @gzharun, thank you for the fix!
