### ISSUE TITLE
Crash with latest version (v1.27) on UE 5.1.1

### ISSUE THREAD

**Issue by MSGames30** [CesiumGS/cesium-unreal#1123]
Hi , 

I just updated the plugin to the latest version (today version  1.27 / UE5.1.1), since then I cannot launch my project anymore .
If I disable the cesium plugin in the uproject file, projects launch well.

Here's the error log : 

```
[2023.06.08-19.35.43:486][  0]LogShaderCompilers: Warning: 3 Shader compiler errors compiling WorldGridMaterial for platform PCD3D_SM6:
[2023.06.08-19.35.43:486][  0]LogShaderCompilers: Warning: Shader debug info dumped to: "E:/Git Unreal/PROJECTNAME/Saved/ShaderDebugInfo/PCD3D_SM6/WorldGridMaterial/Default/DepthPosOnlyNoPixelPipeline/FCesiumPointAttenuationVertexFactory/TDepthOnlyVS(true)/0"
C:/Program Files/Epic Games/UE_5.1/Engine/Shaders/Private/PositionOnlyDepthVertexShader.usf(23,57): Shader TDepthOnlyVS<true>, Permutation 0, VF FCesiumPointAttenuationVertexFactory:
	/Engine/Private/PositionOnlyDepthVertexShader.usf(23,57): error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput'
	        const uint EyeIndex =  (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) ;
	                                                         ~~~~~ ^

[2023.06.08-19.35.43:486][  0]LogShaderCompilers: Warning: C:/Program Files/Epic Games/UE_5.1/Engine/Shaders/Private/PositionOnlyDepthVertexShader.usf(26,64): Shader TDepthOnlyVS<true>, Permutation 0, VF FCesiumPointAttenuationVertexFactory:
	/Engine/Private/PositionOnlyDepthVertexShader.usf(26,64): error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput'
	        ResolvedView =  (ResolveView( (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) )) ;
	                                                                ~~~~~ ^

[2023.06.08-19.35.43:486][  0]LogShaderCompilers: Warning: C:/Program Files/Epic Games/UE_5.1/Engine/Shaders/Private/PositionOnlyDepthVertexShader.usf(): Shader TDepthOnlyVS<true>, Permutation 0, VF FCesiumPointAttenuationVertexFactory:
	D3DCompileToDxil failed. Error code: Erreur non spécifiée (0x80004005).

[2023.06.08-19.35.43:486][  0]LogWindows: Error: appError called: Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp] [Line: 4668] 
  /Engine/Private/PositionOnlyDepthVertexShader.usf:23:57: error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput'
	        const uint EyeIndex =  (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) ;
	                                                         ~~~~~ ^
  /Engine/Private/PositionOnlyDepthVertexShader.usf:26:64: error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput'
	        ResolvedView =  (ResolveView( (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) )) ;
	                                                                ~~~~~ ^
  D3DCompileToDxil failed. Error code: Erreur non spécifiée (0x80004005).
Failed to compile default material /Engine/EngineMaterials/WorldGridMaterial.WorldGridMaterial!
```

**Comment by kring** [comment]
@MSGames30 I can't reproduce that crash. I tried installing the plugin from the Epic Launcher, and I also tried forcing my system to use D3D12 / SM6 (because I see that in your error messages). The shaders compile fine, and the plugin works.

Can you please try the [Cesium for Unreal Samples](https://github.com/CesiumGS/cesium-unreal-samples/releases/latest) project and see if you have the same problem there?

**Comment by MSGames30** [comment]
Hi, 

Thanks for the reply, Sample project runs with no problem.
I've tried to enable the other plugins I use but still no problem.

I've tried older versions of my project , all of them crashes.

**Comment by kring** [comment]
Hmm I'm not sure. I think you'll have to go through the settings carefully and see what's different between the working and non-working projects. I'd start with RHI-related settings. For example, if your (non-working) project is configured to use D3D12, try enabling that in the working project and see if it breaks.

**Comment by MSGames30** [comment]
So far I've tried to enable all the plugins from my project, copied my defaultengine.ini settings to the sample project, migrated all my Cesium related content to the sample project,  It opens and run with no problem.

Will try to look at the settings with projects side by side, I for now went back to 1.26 .

**Comment by Stollentroll1984** [comment]
Have the same problem here. You have to enable "Instanced Stereo" to reproduce the issue.

**Comment by Ruveron** [comment]
Same problem here since the new version.
I confirm that with "Instanced Stereo" true, i've compil problem but when off, no problem.

**Comment by markusatbentley** [comment]
same issue here: after the update opening the project had following effect: 
Unreal engine 5.1.1- opening loading till 45% and compiling shaders, after last shader compiled following crash: 

Fatal error: [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Private\ShaderCompiler\ShaderCompiler.cpp] [Line: 4668] /Engine/Private/PositionOnlyDepthVertexShader.usf:23:57: error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput' const uint EyeIndex = (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) ; ~~~~~ ^ /Engine/Private/PositionOnlyDepthVertexShader.usf:26:64: error: no member named 'InstanceId' in 'FPositionOnlyVertexFactoryInput' ResolvedView = (ResolveView( (IsInstancedStereo() ? ( (Input.InstanceId) & 1) : 0) )) ; ~~~~~ ^ D3DCompileToDxil failed. Error code: Unbekannter Fehler (0x80004005). Failed to compile default material /Engine/EngineMaterials/WorldGridMaterial.WorldGridMaterial!

(strange as I don't use a D drive)

I'm using it as VR project.

Disabling Cesium helped to open the project at least

**Comment by markusatbentley** [comment]
Update from my side: I worked with a colleague on a shared Git project - he was able to open the project and me not (only after deactivating Cesium) - unintentionally I used Unreal Engine 5.1.1 and he 5.0.1   - so when I used 5.0.1 again it worked for me

**Comment by markusatbentley** [comment]
new update: fresh download of Unreal Engine 5.1.1 + latest Cesium from Marketplace -> same crash as before (see above) 
UE 5.2 + latest Cesium from Marketplace -> same crash as before (see above) 

so currently Cesium plugin is not usable for me anymore from the marketplace, latest updates let all crash when loading the project (till 45  % - compiling shaders, after last shader compiled error like in message above)

I worked with UE 5.0.1 with an earlier version of the Cesium plugin - and had no problems.

**Comment by MSGames30** [comment]
> new update: fresh download of Unreal Engine 5.1.1 + latest Cesium from Marketplace using UE VR template as a start -> same crash as before (see above) UE 5.2 + latest Cesium from Marketplace + using UE VR template as a start-> same crash as before (see above)
> 
> we also tried the Cesium plugin via Git, same issues.
> 
> So currently Cesium plugin is not usable for me for VR projects anymore from the marketplace, latest updates let VR projects crash when loading the project (till 45 % - compiling shaders, after last shader compiled error like in message above)
> 
> I worked with UE 5.0.1 with an earlier version of the Cesium plugin - and had no problems. @kring

You can use the 1.26 version of the plugin it runs fine on 5.0 and 5.1 and is not that old:

https://github.com/CesiumGS/cesium-unreal/releases/tag/v1.26.0

**Comment by kring** [comment]
We're actively working on a fix for this. In the meantime, you can either downgrade to v1.26.0, or perhaps you can disable Instanced Stereo?
